#ifndef CONFIG_H
#define CONFIG_H

#define EMULATOR_WINDOW_TITLE "Chip8 Emulator"
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define SCALE 10
#define WINDOW_WIDTH CHIP8_WIDTH * SCALE
#define WINDOW_HEIGHT CHIP8_HEIGHT * SCALE  

#define CHIP8_TOTAL_DATA_REGISTERS 16

#endif